/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void Main_win(PApplet appc, GWinData data) { //_CODE_:window1:361951:
    appc.background(20);
    appc.textSize(60); 
    appc.text("TeacherDex", 85, 90); 
    appc.fill(100, 255, 255);
} //_CODE_:window1:361951:

public void Index_button(GButton source, GEvent event) { //_CODE_:button1:233498:
  window1.setVisible(false);
  window2.setVisible(true);
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:233498:

public void Duel_button(GButton source, GEvent event) { //_CODE_:button2:227004:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:227004:

synchronized public void Index_win(PApplet appc, GWinData data) { //_CODE_:window2:604964:
   appc.background(30);
   appc.textSize(50); 
   appc.text("TeacherGallery", 85, 90); 
   appc.fill(100, 100, 255);
} //_CODE_:window2:604964:

public void Home_button(GButton source, GEvent event) { //_CODE_:button3:786171:
  window1.setVisible(true);
  window2.setVisible(false);
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button3:786171:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Main");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 500, 500, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.CLOSE_WINDOW);
  window1.addDrawHandler(this, "Main_win");
  button1 = new GButton(window1, 172, 178, 142, 69);
  button1.setText("Index");
  button1.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  button1.addEventHandler(this, "Index_button");
  button2 = new GButton(window1, 171, 309, 140, 72);
  button2.setText("Duel");
  button2.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button2.addEventHandler(this, "Duel_button");
  window2 = GWindow.getWindow(this, "Window title", 0, 0, 500, 500, JAVA2D);
  window2.noLoop();
  window2.setActionOnClose(G4P.CLOSE_WINDOW);
  window2.addDrawHandler(this, "Index_win");
  button3 = new GButton(window2, 9, 9, 82, 24);
  button3.setText("Home ");
  button3.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button3.addEventHandler(this, "Home_button");
  window1.loop();
  window2.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton button1; 
GButton button2; 
GWindow window2;
GButton button3; 
